name: ci

on:
    push:
        branches:
            - main
            - master
    pull_request:
        branches:
            - main
            - master

jobs:
    test_lint:
        runs-on: ubuntu-latest
        if: ${{ !github.event.created }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - run: npm install -g yarn
            - run: yarn
            - name: Making sure 'yarn run lint' and 'yarn run format' does not changes anything.
              run: |
                  yarn run lint
                  yarn run format
    test_node:
        runs-on: ${{ matrix.os }}
        needs: test_lint
        strategy:
            matrix:
                node: ['14', '13', '12']
                os: [windows-latest, ubuntu-latest]
        name: Test with Node v${{ matrix.node }} on ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}
            - run: npm install -g yarn
            - run: yarn
            - run: yarn run test
